name: Super linter

on:
  pull_request:
    branches: [master, main]

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commit history + checkout
        uses: actions/checkout@v3
      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest
      - name: Install Node.js and make a cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install

      - name: ESLint - Detect lint errors
        run: pnpm eslint --ignore-path ./src/prisma/**/*.ts --ext .js,.ts -c .eslintrc.json .

  jest:
    needs: eslint
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commit history + checkout
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install Node.js and make a cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Jest - Verify tests
        run: pnpm jest

  build-ts:
    needs: [eslint, jest]
    runs-on: ubuntu-latest
    steps:
      - name: Fetch commit history + checkout
        uses: actions/checkout@v3

      - name: pnpm setup
        uses: pnpm/action-setup@v2.2.2
        with:
          version: latest

      - name: Install Node.js and make a cache
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build - try to build app
        run: pnpm tsc --build


  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: github/super-linter@v4
        env:
          LINTER_RULES_PATH: /
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: master
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TYPESCRIPT_ES_CONFIG_FILE: .eslintrc.json
          VALIDATE_TYPESCRIPT_ES: true
          TYPESCRIPT_STANDARD_TSCONFIG_FILE: tsconfig.json
  